spring:
  application:
    name: treatment-plan
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:treatment-plan;DB_CLOSE_DELAY=-1
    username: sa
    password: